<?xml version="1.0" encoding="utf-8"?><Database Name="FoodRecipeDB" Class="FoodRecipeDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=FoodRecipeDB;Integrated Security=True" SettingsObjectName="FoodRecipeApp.Properties.Settings" SettingsPropertyName="FoodRecipeDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DISH" Member="DISHes">
    <Type Name="DISH">
      <Column Name="ID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DISH_NAME" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="DISH_IMAGE" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DISH_DESCRIPTION" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DISH_INGREDIENT" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DISH_VIDEO" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DISH_FAVORITE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DISH_DISH_TYPE" Member="DISH_TYPEs" ThisKey="ID" OtherKey="ID" Type="DISH_TYPE" />
      <Association Name="DISH_RECIPE" Member="RECIPEs" ThisKey="ID" OtherKey="ID" Type="RECIPE" />
      <Association Name="DISH_SEARCH" Member="SEARCHes" ThisKey="ID" OtherKey="ID" Type="SEARCH" />
    </Type>
  </Table>
  <Table Name="dbo.DISH_TYPE" Member="DISH_TYPEs">
    <Type Name="DISH_TYPE">
      <Column Name="ID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TYPEID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DISH_DISH_TYPE" Member="DISH" ThisKey="ID" OtherKey="ID" Type="DISH" IsForeignKey="true" />
      <Association Name="TYPEDB_DISH_TYPE" Member="TYPEDB" ThisKey="TYPEID" OtherKey="TYPEID" Type="TYPEDB" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IMAGES" Member="IMAGEs">
    <Type Name="IMAGE">
      <Column Name="ID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="STEP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="STEP_IMAGE" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="RECIPE_IMAGE" Member="RECIPE" ThisKey="ID,STEP" OtherKey="ID,STEP" Type="RECIPE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RECIPE" Member="RECIPEs">
    <Type Name="RECIPE">
      <Column Name="ID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="STEP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="STEP_DESCRIPTION" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="RECIPE_IMAGE" Member="IMAGE" ThisKey="ID,STEP" OtherKey="ID,STEP" Type="IMAGE" Cardinality="One" />
      <Association Name="DISH_RECIPE" Member="DISH" ThisKey="ID" OtherKey="ID" Type="DISH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SEARCH" Member="SEARCHes">
    <Type Name="SEARCH">
      <Column Name="ID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OTHERNAME" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DISH_SEARCH" Member="DISH" ThisKey="ID" OtherKey="ID" Type="DISH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TYPEDB" Member="TYPEDBs">
    <Type Name="TYPEDB">
      <Column Name="TYPEID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TYPEDB_NAME" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Association Name="TYPEDB_DISH_TYPE" Member="DISH_TYPEs" ThisKey="TYPEID" OtherKey="TYPEID" Type="DISH_TYPE" />
    </Type>
  </Table>
</Database>