GO 
CREATE DATABASE FoodRecipeDB
GO
USE FoodRecipeDB
GO

CREATE TABLE DISH
(
	ID CHAR(10),
	DISH_NAME NVARCHAR(60),
	DISH_IMAGE NVARCHAR(150),
	DISH_DESCRIPTION NTEXT,
	DISH_INGREDIENT NTEXT,
	DISH_VIDEO VARCHAR(100),
	DISH_FAVORITE BIT,
	CONSTRAINT PK_D PRIMARY KEY (ID)
)

CREATE TABLE DISH_TYPE
(
	ID CHAR(10),
	TYPEID CHAR(10),
	CONSTRAINT PK_DT PRIMARY KEY (ID,TYPEID)
)

CREATE TABLE TYPEDB
(
	TYPEID CHAR(10),
	TYPEDB_NAME NVARCHAR(60),
	CONSTRAINT PK_T PRIMARY KEY (TYPEID)
)

CREATE TABLE RECIPE
(
	ID CHAR(10),
	STEP INT,
	STEP_DESCRIPTION NTEXT,
	CONSTRAINT PK_R PRIMARY KEY (ID, STEP)
)

CREATE TABLE IMAGES
(
	ID CHAR(10),
	STEP INT,
	STEP_IMAGE NVARCHAR(150),
	CONSTRAINT PK_IMG PRIMARY KEY (ID, STEP)
)

CREATE TABLE SEARCH
(
	ID CHAR(10),
	OTHERNAME NVARCHAR(50),
	CONSTRAINT PK_S PRIMARY KEY (ID,OTHERNAME)
)

-----------------------------------------------------------

ALTER TABLE RECIPE
ADD CONSTRAINT FK_R_D FOREIGN KEY (ID) REFERENCES DISH (ID)

ALTER TABLE IMAGES
ADD CONSTRAINT FK_IMG_R FOREIGN KEY (ID, STEP) REFERENCES RECIPE (ID, STEP)

ALTER TABLE SEARCH
ADD CONSTRAINT FK_S_D FOREIGN KEY (ID) REFERENCES DISH (ID)

ALTER TABLE DISH_TYPE
ADD CONSTRAINT FK_D_T FOREIGN KEY (ID) REFERENCES DISH (ID)

ALTER TABLE DISH_TYPE
ADD CONSTRAINT FK_DT_T FOREIGN KEY (TYPEID) REFERENCES TYPEDB (TYPEID)

-----------------------------------------------------------------

INSERT INTO TYPEDB VALUES('T1', N'Bánh')
INSERT INTO TYPEDB VALUES('T2', N'Món mặn')
INSERT INTO TYPEDB VALUES('T3', N'Món xào')
INSERT INTO TYPEDB VALUES('T4', N'Bò')
INSERT INTO TYPEDB VALUES('T5', N'Gà')