GO 
CREATE DATABASE FoodRecipeDB
GO
USE FoodRecipeDB
GO

CREATE TABLE DISH
(
	ID CHAR(10),
	DISH_NAME NVARCHAR(50),
	DISH_IMAGE IMAGE,
	DISH_DESCRIPTION NTEXT,
	DISH_TYPE NVARCHAR(30),
	DISH_LEVEL NVARCHAR(20),
	CONSTRAINT PK_D PRIMARY KEY (ID)
)

CREATE TABLE RECIPE
(
	ID CHAR(10),
	STEP INT,
	STEP_DESCRIPTION NTEXT,
	CONSTRAINT PK_R PRIMARY KEY (ID, STEP)
)

CREATE TABLE IMAGES
(
	ID CHAR(10),
	STEP INT,
	STEP_IMAGE IMAGE,
	CONSTRAINT PK_IMG PRIMARY KEY (ID, STEP)
)

CREATE TABLE DISH_INGREDIENTS
(
	ID CHAR(10),
	ID_INGREDIENT CHAR(10),
	QUANTITY NVARCHAR(30),
	CONSTRAINT PK_DI PRIMARY KEY (ID, ID_INGREDIENT)
)

CREATE TABLE INGREDIENTS
(
	ID_INGREDIENT CHAR(10),
	INGREDIENT_NAME NVARCHAR(50),
	INGREDIENT_TYPE NVARCHAR(30),
	CONSTRAINT PK_ING PRIMARY KEY (ID_INGREDIENT)
)

CREATE TABLE SEARCH
(
	FULLNAME NVARCHAR(50),
	OTHERNAME NVARCHAR(50),
	CONSTRAINT PK_S PRIMARY KEY (FULLNAME)
)

-----------------------------------------------------------

ALTER TABLE RECIPE
ADD CONSTRAINT FK_R_D FOREIGN KEY (ID) REFERENCES DISH (ID)

ALTER TABLE IMAGES
ADD CONSTRAINT FK_IMG_R FOREIGN KEY (ID, STEP) REFERENCES RECIPE (ID, STEP)

ALTER TABLE DISH_INGREDIENTS
ADD CONSTRAINT FK_D_ING FOREIGN KEY (ID) REFERENCES DISH (ID)

ALTER TABLE DISH_INGREDIENTS
ADD CONSTRAINT FK_DI_I FOREIGN KEY (ID_INGREDIENT) REFERENCES INGREDIENTS (ID_INGREDIENT)

ALTER TABLE DISH
ADD CONSTRAINT FK_D_S FOREIGN KEY (DISH_NAME) REFERENCES SEARCH (FULLNAME)

ALTER TABLE INGREDIENTS
ADD CONSTRAINT FK_ING_S FOREIGN KEY (INGREDIENT_NAME) REFERENCES SEARCH (FULLNAME)


-----------------------------------------------------------------

